/**
 * ApiGeneratedChatGPT35
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from "./ApiClient";
import ArticleCreateDto from "./model/ArticleCreateDto";
import ArticleDto from "./model/ArticleDto";
import ArticleUpdateDto from "./model/ArticleUpdateDto";
import ArticleApi from "./api/ArticleApi";

/**
 * JS API client generated by OpenAPI Generator.<br>
 * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
 * <p>
 * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
 * <pre>
 * var ApiGeneratedChatGpt35 = require('index'); // See note below*.
 * var xxxSvc = new ApiGeneratedChatGpt35.XxxApi(); // Allocate the API class we're going to use.
 * var yyyModel = new ApiGeneratedChatGpt35.Yyy(); // Construct a model instance.
 * yyyModel.someProperty = 'someValue';
 * ...
 * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
 * ...
 * </pre>
 * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
 * and put the application logic within the callback function.</em>
 * </p>
 * <p>
 * A non-AMD browser application (discouraged) might do something like this:
 * <pre>
 * var xxxSvc = new ApiGeneratedChatGpt35.XxxApi(); // Allocate the API class we're going to use.
 * var yyy = new ApiGeneratedChatGpt35.Yyy(); // Construct a model instance.
 * yyyModel.someProperty = 'someValue';
 * ...
 * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
 * ...
 * </pre>
 * </p>
 * @module index
 * @version 1.0
 */
export {
  /**
   * The ApiClient constructor.
   * @property {module:ApiClient}
   */
  ApiClient,

  /**
   * The ArticleCreateDto model constructor.
   * @property {module:model/ArticleCreateDto}
   */
  ArticleCreateDto,

  /**
   * The ArticleDto model constructor.
   * @property {module:model/ArticleDto}
   */
  ArticleDto,

  /**
   * The ArticleUpdateDto model constructor.
   * @property {module:model/ArticleUpdateDto}
   */
  ArticleUpdateDto,

  /**
   * The ArticleApi service constructor.
   * @property {module:api/ArticleApi}
   */
  ArticleApi,
};
